### PR TITLE
Added documentation about form_logo.png, closes #34

### LINKED ISSUE #34: Include form_logo.png feature in documentation

### PR DESCRIPTION
**Pull request by MartijnR**
Not crazy about this, but I think we should include it.

### CODE REVIEW

**Comment by lognaturel** [comment]
This is no longer supported by ODK Collect -- users are instead encouraged to design their own landing/branding screens explicitly using media includes. Perhaps it should just say "this image MAY be shown by the client"

**Comment by MartijnR** [comment]
I think it makes sense to not have this feature at all. The only issue I have with the proper approach that you started using is that I'd like a 'note' with a media label that serves as logo to be display above the form title, but that's pretty minor so I'll get over that.

**Comment by lognaturel** [comment]
I'm happy either way! I do think specifying a logo makes more sense for a web client like Enketo so if you prefer to document it that works for me.

**Comment by MartijnR** [comment]
Let's be strict. It's a good feature, but poorly implemented. True, that it makes more sense for a web client indeed.

**Pull request closed without merging**
