### PR TITLE
Update docs for normalize-space()

### LINKED ISSUE #242: Add documentation for the new `normalize-space` XPath function in Javarosa
A recent pull request in Javarosa for the normalize-space function requires documentation for users. Its definition is here: https://www.w3.org/TR/1999/REC-xpath-19991116/#function-string-length

I recommend it be placed with other string functions at:
https://github.com/opendatakit/xforms-spec/blob/gh-pages/_sections/30-bindings.md#xpath-functions

### PR DESCRIPTION
**Pull request by jkpr**
Closes #242.

I matched what was described for `string-length`.

### CODE REVIEW

**Review by MartijnR — COMMENTED** [review]
Thanks! Would it be problematic to avoid deviating? Especially for XPath 1.0, there are clients that will not deviate and provide different results because they use off-the-shelf or native XPath 1.0 evaluators (Enketo, @tiritea's iOS app).

It would be useful for XPath wizards that do `//item/name[normalize-space() = 'Jane Doe']` or something like that.

**Comment by jkpr** [comment]
Interesting! I am no wizard 🧙‍♂️ so I did not think of that! I was wondering how / why the zero-arg form would be useful.

@lognaturel is planning to get to the zero-arg form eventually. I would do it myself, but I am not certain how to write a good failing test in Javarosa. See my attempt here (down at the bottom is a discussion and link to a git diff on github): https://github.com/opendatakit/javarosa/pull/467

**Comment by lognaturel** [comment]
Agreed, the spec can match XPath 1.0. In the very short term, JavaRosa/Collect may deviate but that's fine.

So in practice, @jkpr, that just means saying "As in XPath 1.0" with the link to the reference. Sorry I didn't think of that decision point!

**Comment by MartijnR** [comment]
Great. 

(Now, of course, I'm wondering if the same could be done for the old string-length()... ;))

**Comment by lognaturel** [comment]
> I'm wondering if the same could be done for the old string-length()

Yes, I was thinking we should clean that up, too. 😊

**Comment by jkpr** [comment]
Am I understanding correctly, then, that I should change the commit to say: 

> As in [XPath 1.0](https://www.w3.org/TR/1999/REC-xpath-19991116/#function-normalize-space)

instead of updating it when we have the zero-arg form?

**Comment by lognaturel** [comment]
Exactly, @jkpr. The specification is the ideal that ties all the different tools in the ODK ecosystem together. Sometimes one tool or another may be slightly out of sync with that ideal and in that case, documentation for that specific tool will reflect that reality.

**Comment by jkpr** [comment]
I didn't know if force updating one commit on this branch would delete this pull request, so I made another pull request: #247.

**Pull request closed without merging**
