### PR TITLE
fixed: links to and from encryption sub-spec, closes #209

### LINKED ISSUE #209: Fix links to and from encryption spec

### PR DESCRIPTION
**Pull request by MartijnR**
I hope you've learned not to trust me!

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Maybe we should add a PR template to keep ourselves honest! I am not always good about running these either. When I have to check a box that says "I actually ran this", I tend to do it. 😆

**Comment by MartijnR** [comment]
Yes, maybe. In this case, the links worked locally, but the issue was gh-pages serving on a path. I think there must be a way to set such a path in `jekyll serve` to avoid that.

**Comment by lognaturel** [comment]
Oh, I see. Hmm, I wouldn't have known that so even if I had run it locally (which I should have), that probably wouldn't have helped.  ¯\_(ツ)_/¯ Sometimes there's no substitute for just pushing to production and seeing what happens. Good thing you checked the live page because I didn't do that either. 🤕

**Comment by MartijnR** [comment]
Embarrassingly it's still not correct... Sorry. Will send another fix and figure out how to properly run locally to test them.

**Comment by lognaturel** [comment]
🤦‍♀️ 🤦‍♀️  I did check it works locally...

**Pull request merged**
