### PR TITLE
Add bundler for managing dependencies

### LINKED ISSUE #118: Include some kind of build file for getting dependencies
E.g. a `Gemfile` for bundler

### PR DESCRIPTION
**Pull request by alxndrsn**
I hope this is helpful!

Closes #118

### CODE REVIEW

**Comment by MartijnR** [comment]
Yes, I think so. Thanks! 

Should `gem install` in readme.md be `bundle install`?

**Comment by lognaturel** [comment]
Yaaaay, this is great!

I'd personally remove the "Requirements for running locally" section and just add "run `bundle install`" before the jekyll command in "Run locally".

**Comment by alxndrsn** [comment]
> Should `gem install` in readme.md be `bundle install`?

Yes, thanks for spotting!

@lognaturel I'll remove the old instructions, too

**Comment by lognaturel** [comment]
So wonderful. 🚀

**Pull request merged**
