### PR TITLE
Document last-saved secondary instances (for auto-fill)

### PR DESCRIPTION
**Pull request by cooperka**
Related PR: https://github.com/opendatakit/collect/pull/2882

cc @lognaturel

### CODE REVIEW

**Comment by lognaturel** [comment]
Sorry about the delay getting back to you on this, @cooperka! This feels more tutorial-like than the rest of the specification. I think it'd be great content for user-facing documentation. In particular, we don't mention Collect or any other specific implementation of the spec in this document.

I would tend to add a new section below https://opendatakit.github.io/xforms-spec/#binary-endpoints called something like "Virtual endpoints" and have a table with `jr://instance/last-saved` as the only row for now (with more probably coming - https://forum.opendatakit.org/t/odk-xforms-spec-proposal-introduce-a-virtual-instance-for-metadata/19122).

I think these sentences you had feel appropriate either in the table or below:
Note that the "last-saved" terminology is significant -- it refers to the form instance that was **saved** most recently (as opposed to last-opened or last-finalized, for example).

The most common use case for this feature is to "auto-fill" specific form fields with the last-saved value via [`odk-instance-first-load`](#event:odk-instance-first-load).

Hopefully this makes sense and doesn't feel too nit-picky!

**Comment by cooperka** [comment]
Thanks for the feedback @lognaturel, done.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
That looks perfect to me! Will give @MartijnR a day or two in case he has feedback on the contents or organization. Thanks so much. 🙏

**Review by MartijnR — APPROVED** [review]

**Comment by MartijnR** [comment]
Looks great. Thanks @cooperka @lognaturel !

**Pull request merged**
