### PR TITLE
fixed: links from encryption page to main page, closes #209

### LINKED ISSUE #209: Fix links to and from encryption spec

### PR DESCRIPTION
**Pull request by MartijnR**
Now we should have the same URL structure as on github pages so we can test links across pages locally.

### CODE REVIEW

**Comment by MartijnR** [comment]
also snuck in a spec correction

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Nth time is a charm? 🤞

**Comment by lognaturel** [comment]
Seems to be live and working!! 👏

**Comment by MartijnR** [comment]
Woohooo, i mastered Jekyll finally!

**Comment by lognaturel** [comment]
🏆 🎖

**Pull request merged**
